export default {
  BackgroundImage: require('../assets/images/maxresdefault.jpeg'),
  bedroom: require('../assets/images/bedroom.jpeg'),
  livingroom: require('../assets/images/livingroom.jpeg'),
  camera: require('../assets/images/camera.jpeg'),
  appliances: require('../assets/images/appliances.png'),
  storage: require('../assets/images/storage.jpeg'),
  packages: require('../assets/images/packages.png'),
  home: require('.././assets/images/home_updated.jpeg'),
  menu: require('.././assets/images/menu.png'),
  cart: require('.././assets/images/shopping.png'),
  people: require('.././assets/images/person.png'),
  sofa: require('.././assets/images/sofaFront.jpeg'),
  gift: require('.././assets/images/giftUpdated.jpeg'),
};
